sonarqube_analyzer:
  stage: test
  script:
    - cd implementation
    - sonar-runner
    - cd ..

sonarqube_reporter:
  stage: test
  script:
    - cd implementation
    - sonar-scanner -Dsonar.analysis.mode=preview -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
    - cd ..

deploy:
  stage: deploy
  script:
    make -C implemantation deploy-cd
