# Generated by Django 2.2.6 on 2019-10-15 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_auto_20191010_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmailbox',
            name='initiated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes_passive', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmailbox',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes_active', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmailbox',
            name='last_sent',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='meet.ChatMailbox'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='initiated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_passive', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_active', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='since',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marker',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meetexternallinks',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='meet.Meet'),
        ),
        migrations.AlterField(
            model_name='meetstar',
            name='meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='meet.Meet'),
        ),
        migrations.AlterField(
            model_name='meetstar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to=settings.AUTH_USER_MODEL),
        ),
    ]
