# Generated by Django 2.2.6 on 2019-10-15 05:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_auto_20191015_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='key',
            field=models.UUIDField(default=uuid.UUID('1edc0eca-648a-4cc3-aa0a-89adaa409534')),
        ),
    ]
