# Generated by Django 2.2.6 on 2019-10-15 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0004_auto_20191015_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
