# Generated by Django 2.2.6 on 2019-10-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0006_auto_20191015_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetstar',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
