# Generated by Django 2.2.6 on 2019-10-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0007_auto_20191021_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetstar',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
