@startuml
hide circle
hide empty methods
hide empty attributes

package "templates" as tpls {
  class "Some page" as pg1 <<page>>
  class "Other page" as pg2 <<page>>
}

package "views" as vws {
  class "Some View" as vw1 <<controller>>
  class "Other View" as vw2 <<controller>>
}

pg1 -.-> vw2: {method=get}
pg2 -.-> vw2: {method=get}
pg1 -.-> vw1: {method=get}
pg2 -.-> vw1: {method=get}

pg1 <-.- vw1: {method=get, result=Ok}
pg2 <-.- vw2: {method=get, result=Ok}

@enduml
